.gitlab-ci.yml, Makefile
- https://github.com/metanorma/metanorma-docker/issues/6
=> Add GitLab CI config

README.adoc
- https://github.com/metanorma/metanorma-docker/issues/11
=> Add build badge to README

.travis.yml, Makefile, README.adoc
- https://github.com/metanorma/metanorma-docker/issues/13#issuecomment-479753956
=> Add description of push process by CI

Makefile
- #21 
@ronaldtse  Once CI passed I will merge & tag it
=> #21 Update metanorma version to 1.2.2

README.adoc
- Updates were done to the docker image that changed how the image is invoked. 
- Fixes #19 
- if there's more needed for updates to the file feel free to reject PR.  Was just an easy change I thought I could contribute! 👍
=> Update README with `metanorma compile`

README.adoc
This commit includes a what's included section, and this list out a high level overview of the software/packages included with the docker image.
Closes #30
=> Update document with what's include section

Makefile
=> #39 upgrare ruby version to 2.6

.github/workflows/docker-mn.yml, metanorma/Dockerfile.in
- https://github.com/metanorma/metanorma-docker/issues/43
=> install xml2rfc

.github/workflows/docker-mn.yml
=> metanorma/metanorma-cli#121 Add repository_dispatch event

.github/workflows/docker-metanorma.yml, .github/workflows/docker-mn.yml
Build both metanorma/metanorma and metanorma/mn containers on:
* push to master
* release tags (`v...`)
* pull requests
Release metanorma/metanorma container on:
* release tags (`v...`)
Release metanorma/mn container on:
* push to master
* release tags (`v...`)
=> Update GHA workflow conditions

Dockerfile.ruby.in, Dockerfile.ubuntu.in, Makefile
=> #51 use --disable-march-tune-native for sassc building

Dockerfile.ruby.in, Dockerfile.ubuntu.in
- https://github.com/rbenv/ruby-build/issues/1211
=> Fix missing libgdbm5

.github/workflows/docker-metanorma.yml, .github/workflows/docker-mn.yml, .github/workflows/release.yml, Makefile, README.adoc, VERSION.mak
=> Auto-tag on metanorma-cli release

.github/workflows/docker-mn.yml
=> #86 trigger samples repos on push to master

.github/workflows/docker-mn.yml
=> #90 trigger samples deployment only for release

Dockerfile.ruby.in, Dockerfile.ubuntu.in
=> #62 Add font volume

.github/workflows/docker-metanorma.yml, .github/workflows/docker-mn.yml, Dockerfile.ruby.in, Dockerfile.ubuntu.in, Makefile, metanorma/Gemfile.in, mn/Gemfile.in
=> 112 fix insecure BUNDLE_RUBYGEMS__PKG__GITHUB__COM

.dive-ci, .github/workflows/docker-metanorma.yml, .github/workflows/docker-mn.yml, Makefile
=> #109 add dive step to CI

ubuntu.sh
- ❎ Breaking changes (list related PRs)
- ❎ Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
- ❎ External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
- ❎ Gem with native library introduced
=> #120 remove idnits installation

Dockerfile.ubuntu.in, ubuntu.sh
=> #127 remove latexml installation

Dockerfile.ruby.in, Dockerfile.ubuntu.in
=> #133 Upgrade ruby version to 3.1

Dockerfile.ubuntu, ubuntu.sh
=> Added cmake to container

Dockerfile.ruby
=> #140 use ruby 3.1.1

.github/workflows/build-push.yml, Makefile, ubuntu.sh
=> Refactor GHA and update plantuml-install script branch

.github/workflows/build-push.yml, docs/description.md
=> Update tag format, fixes #148

.github/workflows/build-push.yml, Dockerfile.alpine, Makefile, metanorma-alpine/Gemfile, mn-alpine/Gemfile
Add Alpine version of container (linux/amd64), fixes #143
=> Add Alpine version of container (linux/amd64)

metanorma-ruby/Gemfile
Related to https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/pull/5
=> Add sassc gem

Dockerfile.alpine
=> Temporaly enable verbose logging for bundle install on alpine

Dockerfile.alpine, Dockerfile.ruby, Dockerfile.ubuntu
- https://github.com/metanorma/metanorma-docker/actions/runs/3001168868
=> Fix pngcheck gem installation

.github/workflows/build-push.yml
=> metanorma/mnconvert#194 add mn-samples-ieee-private to test matrix

.github/workflows/build-push.yml
=> #172 enable strict mode

Dockerfile.ubuntu
- https://github.com/metanorma/metanorma-docker/actions/runs/4282075766/jobs/7455890903
=> Fix psych build on ubuntu image

Dockerfile.alpine
=> #179 fix plantuml installation linux/arm64

.github/workflows/build-push.yml
=> #177 move to own dive action

Dockerfile.alpine
=> metanorma/metanorma#356 use plantuml-install script for alpine

.github/workflows/build-push-windows.yml, .github/workflows/build-push.yml, Dockerfile.windows
Originally from #194 
- **#193: add Dockerfile.windows and sample workflow**
- **chore: update build conditions in windows workflow**
- **GHA optimization**
- **Fix GHA**
- **Fix GHA again**
- **GHA: no need to login to ghcr.io**
- **Use Noelware/docker-manifest-action**
- **GHA: Change image name for debug**
- **GHA: fix docker-manifest-action config**
- **Revert IMAGE_NAME**
- **chore: add permissions for build-push**
- **chore: push to both docker hub and ghcr, attempt to set correct tags (and a structure for future testing)**
=> Containers for Windows

.github/workflows/build-push-windows.yml
- Added Windows container testing
- Since it takes up to 10 billable Windows VM hours to run all the tests against an image, we decided to only test one image
=> Add container testing for Windows containers #196

README.adoc
=> chore: update README for windows containers

.github/workflows/build-push.yml
=>  chore(workflow): decrease build time with matrix

Dockerfile.alpine, Dockerfile.ruby, Dockerfile.ubuntu, Dockerfile.windows
=> #206 - remove idnits from Dockerfile

.github/workflows/build-push-windows.yml
=> #212: Remove windows-2019 runner and ltsc2019
